@extends('layouts.admin')

@section('title', 'Audit Trail & Reporting')
@section('subtitle', 'Module 1.7 — system activity log and saved reports')

@section('content')
    <div class="cc-card">
        <p class="text-card-title">Recent Activity</p>

        <div class="mt-md overflow-x-auto">
            <table class="w-full text-left text-body">
                <thead>
                    <tr class="border-b border-border text-section-label text-text-secondary">
                        <th class="py-sm pr-md">When</th>
                        <th class="py-sm pr-md">Account</th>
                        <th class="py-sm pr-md">Action</th>
                        <th class="py-sm pr-md">Module</th>
                        <th class="py-sm pr-md">Description</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-border">
                    @foreach ($auditLogs as $log)
                        <tr>
                            <td class="py-sm pr-md text-text-secondary">{{ $log['created_at'] }}</td>
                            <td class="py-sm pr-md">{{ $log['account'] }}</td>
                            <td class="py-sm pr-md">
                                <span class="cc-chip cc-chip-neutral">{{ ucwords(str_replace('_', ' ', $log['action_type'])) }}</span>
                            </td>
                            <td class="py-sm pr-md text-text-secondary">{{ $log['module'] }}</td>
                            <td class="py-sm pr-md">{{ $log['description'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="cc-card">
        <div class="mb-md flex items-center justify-between">
            <p class="text-card-title">Generated Reports</p>
            <button type="button" class="cc-btn-secondary">+ Generate Report</button>
        </div>

        <div class="overflow-x-auto">
            <table class="w-full text-left text-body">
                <thead>
                    <tr class="border-b border-border text-section-label text-text-secondary">
                        <th class="py-sm pr-md">Report Type</th>
                        <th class="py-sm pr-md">Date Range</th>
                        <th class="py-sm pr-md">Generated By</th>
                        <th class="py-sm pr-md">Generated At</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-border">
                    @foreach ($reports as $report)
                        <tr>
                            <td class="py-sm pr-md font-semibold">{{ ucwords(str_replace('_', ' ', $report['report_type'])) }}</td>
                            <td class="py-sm pr-md text-text-secondary">{{ $report['date_range'] }}</td>
                            <td class="py-sm pr-md">{{ $report['generated_by'] }}</td>
                            <td class="py-sm pr-md text-text-secondary">{{ $report['generated_at'] }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection
